version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-next-test
    ports:
      - '3022:3000'
    volumes:
      - .:/app
      - /app/node_modules
